#!/usr/bin/env bash
# Wrapper that always runs wrangler with the local config generated by setup-kv.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOCAL_CONFIG="$PROJECT_ROOT/.wrangler.local.jsonc"

if [[ ! -f "$LOCAL_CONFIG" ]]; then
    echo "❌ Local Wrangler config not found at $LOCAL_CONFIG"
    echo "Run ./scripts/setup-kv.sh first to generate it."
    exit 1
fi

cd "$PROJECT_ROOT"
WRANGLER_CONFIG="$LOCAL_CONFIG" exec npx wrangler "$@"
